In [1]:
#Import the libraries
import math
import pandas_datareader as pdr
import numpy as np
import pandas as pd
import datetime

In [2]:
df = pd.read_excel("Nifty 500.xlsx")

In [3]:
df = df[df['Volume']>500000]
df.head()

,Ticker,LTP,Open,High,Low,Prev Close,Volume,Buy,Sell,% Change
0,IDEA,9.10,9.00,9.20,8.80,8.85,418346262,False,False,2.82
1,TATAMOTORS,123.35,119.95,124.70,119.70,119.10,71095910,False,False,3.57
2,BEL,108.25,105.45,113.90,104.40,99.20,65821856,False,False,9.12
3,BHEL,36.35,36.00,37.65,35.85,35.25,60898741,False,False,3.12
4,CIPLA,797.70,760.00,814.50,751.35,728.65,56895564,False,False,9.48

In [4]:
df.tail()

,Ticker,LTP,Open,High,Low,Prev Close,Volume,Buy,Sell,% Change
283,SUDARSCHEM,436.0,438.00,445.00,426.35,448.50,513932,False,False,-2.79
284,GODREJCP,683.9,691.20,696.35,680.20,689.10,512185,False,False,-0.75
285,ADVENZYMES,211.0,215.00,215.00,207.75,216.70,510975,False,True,-2.63
286,IIFL,69.0,69.50,70.60,68.20,68.95,509679,False,False,0.07
287,OIL,95.5,95.15,97.00,95.15,94.85,505205,True,False,0.69

In [8]:
# stocks = pd.DataFrame()
for i in df["Ticker"]:
    try:
        stock = pdr.DataReader(i+".NS", data_source='yahoo', start='2000-01-01', end='2021-02-24')
#         stock['Stock'] = i
#         stocks = stocks.append(stock)
        stock.to_excel(f"Nifty500HistoricalStocks/{i}.xlsx")
    except:
        print(i+": No Data")
# stocks.set_index('Stock', inplace=True)

JUBILANT: No Data

In [5]:
stock = pdr.DataReader("IIFL.NS", data_source='yahoo', start='2000-01-01', end='2021-02-24')

In [6]:
i = 'IIFL'

In [7]:
stock.to_excel(f"Nifty500HistoricalStocks/{i}.xlsx")

In [2]:
pdr.DataReader("IIFL.NS", data_source='yahoo', start='2000-01-01', end='2021-02-24')

RemoteDataError: Unable to read URL: https://finance.yahoo.com/quote/IIFL.NS/history?period1=946679400&period2=1614205799&interval=1d&frequency=1d&filter=history
Response Text:
b'<!DOCTYPE html>\n  <html lang="en-us"><head>\n  <meta http-equiv="content-type" content="text/html; charset=UTF-8">\n      <meta charset="utf-8">\n      <title>Yahoo</title>\n      <meta name="viewport" content="width=device-width,initial-scale=1,minimal-ui">\n      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">\n      <style>\n  html {\n      height: 100%;\n  }\n  body {\n      background: #fafafc url(https://s.yimg.com/nn/img/sad-panda-201402200631.png) 50% 50%;\n      background-size: cover;\n      height: 100%;\n      text-align: center;\n      font: 300 18px "helvetica neue", helvetica, verdana, tahoma, arial, sans-serif;\n  }\n  table {\n      height: 100%;\n      width: 100%;\n      table-layout: fixed;\n      border-collapse: collapse;\n      border-spacing: 0;\n      border: none;\n  }\n  h1 {\n      font-size: 42px;\n      font-weight: 400;\n      color: #400090;\n  }\n  p {\n      color: #1A1A1A;\n  }\n  #message-1 {\n      font-weight: bold;\n      margin: 0;\n  }\n  #message-2 {\n      display: inline-block;\n      *display: inline;\n      zoom: 1;\n      max-width: 17em;\n      _width: 17em;\n  }\n      </style>\n  <script>\n    document.write(\'<img src="//geo.yahoo.com/b?s=1197757129&t=\'+new Date().getTime()+\'&src=aws&err_url=\'+encodeURIComponent(document.URL)+\'&err=%<pssc>&test=\'+encodeURIComponent(\'%<{Bucket}cqh[:200]>\')+\'" width="0px" height="0px"/>\');var beacon = new Image();beacon.src="//bcn.fp.yahoo.com/p?s=1197757129&t="+new Date().getTime()+"&src=aws&err_url="+encodeURIComponent(document.URL)+"&err=%<pssc>&test="+encodeURIComponent(\'%<{Bucket}cqh[:200]>\');\n  </script>\n  </head>\n  <body>\n  <!-- status code : 404 -->\n  <!-- Not Found on Server -->\n  <table>\n  <tbody><tr>\n      <td>\n      <img src="https://s.yimg.com/rz/p/yahoo_frontpage_en-US_s_f_p_205x58_frontpage.png" alt="Yahoo Logo">\n      <h1 style="margin-top:20px;">Will be right back...</h1>\n      <p id="message-1">Thank you for your patience.</p>\n      <p id="message-2">Our engineers are working quickly to resolve the issue.</p>\n      </td>\n  </tr>\n  </tbody></table>\n  </body></html>'

In [9]:
# Close = High
stocks0508[stocks0508['Close']==stocks0508['High']]['Volume'].sort_values(ascending=False)

Stock
DISHTV       8728999
HFCL         4010664
HATHWAY      1151893
KPITTECH     1041975
VAKRANGEE     493342
VARROC        263260
Name: Volume, dtype: int64

In [10]:
# Open = Low
stocks0508[stocks0508['Open']==stocks0508['Low']]['Volume'].sort_values(ascending=False)

Stock
TATASTEEL     30559741
NATIONALUM    29447675
SOUTHBANK     17518892
NCC           14088804
GRANULES       9125048
TATASTLBSL     5893051
CDSL           2108622
RAIN           1581793
ENGINERSIN     1547447
JSLHISAR       1541797
CYIENT         1409063
BALRAMCHIN     1192768
SCI            1153710
NAUKRI         1102586
OMAXE          1087895
KPITTECH       1041975
J&KBANK         875843
AEGISCHEM       748212
TATAELXSI       706865
JSL             699395
NIACL           648949
CESC            508666
VAKRANGEE       493342
LTI             373103
AJANTPHARM      334303
POLYCAB         295975
GREAVESCOT      255098
TIMETECHNO      203721
EMAMILTD        135704
LALPATHLAB       98129
TVTODAY          85223
MAHSEAMLES       84836
AFFLE            59372
TEAMLEASE        56405
CGCL             40101
LINDEINDIA       21689
PGHL             11774
VTL              11544
BHARATRAS         9881
AKZOINDIA         5634
VMART             5175
VESUVIUS          2037
Name: Volume, dtype: int64

In [25]:


today

'2021-01-21'

In [26]:
twentyyearsago

'2001-01-26'

In [19]:
# from datetime import datetime

'2021-01-21'

In [14]:
datetime.now()

datetime.datetime(2021, 1, 21, 12, 14, 42, 238715)

In [28]:
twentyYearsAgo = datetime.datetime.now() - datetime.timedelta(days=20*365)
twentyYearsAgo = twentyYearsAgo.strftime('%Y-%m-%d')
today = datetime.datetime.today().strftime('%Y-%m-%d')

df = pdr.DataReader("ZEEL.NS", data_source='yahoo', start=twentyYearsAgo, end=today)

In [29]:
df.head()

                 High        Low       Open      Close      Volume  Adj Close
Date
2002-07-01  39.138096  38.481468  38.847958  38.878498   4031528.0  33.182491
2002-07-02  40.115402  38.542549  38.725796  39.214447  14152321.0  33.469227
2002-07-03  39.764183  38.863228  39.031200  39.565666   8456844.0  33.769001
2002-07-04  40.833111  39.306068  39.871075  39.535126  12745157.0  33.742931
2002-07-05  40.008511  39.015930  40.008511  39.351879   6445895.0  33.586536

In [30]:
df.tail()

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2021-01-15,233.600006,221.600006,229.000000,224.899994,18690401.0,224.899994
2021-01-18,225.899994,214.350006,225.899994,218.000000,13959600.0,218.000000
2021-01-19,226.949997,220.300003,221.000000,225.050003,11383216.0,225.050003
2021-01-20,231.300003,223.750000,224.800003,228.600006,10865893.0,228.600006
2021-01-21,233.899994,228.100006,230.399994,230.199997,5639882.0,230.199997

In [2]:
pdr.DataReader("^CRSLDX", data_source='yahoo', start="2020-12-25", end="2020-12-25")

KeyError: 'Date'

In [15]:
# # importing the libraries
# from bs4 import BeautifulSoup
# import requests

# url="https://www.nseindia.com/get-quotes/equity?symbol=SAIL"

# # Make a GET request to fetch the raw HTML content
# html_content = requests.get(url).text

# # Parse the html content
# soup = BeautifulSoup(html_content, "lxml")
# print(soup.prettify()) # print the parsed data of html

In [16]:
df = pd.read_csv('MW-NIFTY-MIDSMALLCAP-400-11-Aug-2020.csv')

In [17]:
df

,SYMBOL \n,OPEN \n,HIGH \n,LOW \n,PREV. CLOSE \n,LTP \n,CHNG \n,%CHNG \n,VOLUME \n(shares),VALUE,52W H \n,52W L \n,365 D % CHNG \n 09-Aug-2019,30 D % CHNG \n 10-Jul-2020
0,NIFTY MIDSMALLCAP 400,"5,593.85","5,626.90","5,591.80","5,542.85","5,616.15",73.30,1.35,1322150810,"164,658,889,824.95","6,262.30","3,650.20",3.58,5.79
1,EMAMILTD,265.00,308.75,265.00,257.30,308.75,51.45,20.00,9852405,"2,959,071,317.70",357.70,130.95,-17.44,10.95
2,HFCL,14.40,17.15,14.40,14.30,17.15,2.85,19.93,19945663,"325,313,763.53",20.50,8.10,-24.14,3.25
3,HIMATSEIDE,74.75,85.40,73.80,73.35,84.60,11.25,15.34,4938205,"397,377,356.35",165.50,42.95,-47.10,24.22
4,STAR,527.00,616.00,527.00,523.80,603.50,79.70,15.22,6172234,"3,585,080,396.56",616.00,268.00,24.15,24.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
396,AMBER,"1,700.00","1,779.00","1,675.45","1,779.20","1,709.50",-69.70,-3.92,238835,"411,264,316.60","1,809.00",786.20,122.61,15.30
397,JAMNAAUTO,34.40,34.40,31.85,33.95,32.35,-1.60,-4.71,1496831,"49,455,296.24",49.30,21.00,-8.61,6.43
398,HATHWAY,37.70,37.70,37.70,39.65,37.70,-1.95,-4.92,315218,"11,883,718.60",57.30,10.50,-,-
399,RBLBANK,190.75,193.30,180.10,191.30,180.60,-10.70,-5.59,33997206,"6,264,665,149.62",415.00,101.55,-50.20,5.66
400,BIRLACORPN,635.10,635.10,600.00,653.10,604.00,-49.10,-7.52,637702,"387,525,128.38",807.00,372.20,9.53,10.28

In [ ]:
#!/usr/bin/python3
from urllib.request import urlopen as uReq
from bs4 import BeautifulSoup as soup
import requests
import re

_URL = 'https://kissanime.ru/'

# functional
html = requests.get(_URL, headers={"user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"})
bsObj = soup(html.text, "lxml")
print(bsObj)