In [1]:
#Import the libraries
# import math
import pandas_datareader as pdr
import datetime
# import mplfinance as mpf
import os
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_excel("Nifty 500.xlsx")
df = df[df['Volume']>500000]
tickers = df.Ticker.tolist()
tickers = [x+".NS" for x in tickers]

In [3]:
aWeekAgo = (datetime.datetime.today() - datetime.timedelta(days=7)).strftime("%Y-%m-%d")
today = datetime.datetime.today().strftime('%Y-%m-%d')
stocks = pdr.DataReader(tickers, data_source='yahoo', start=aWeekAgo, end=today)

In [4]:
stocks

Attributes Adj Close                                                   \
Symbols      IDEA.NS TATAMOTORS.NS      BEL.NS    BHEL.NS    CIPLA.NS
Date
2021-03-15     10.05    318.549988  137.100006  55.250000  805.500000
2021-03-16     10.15    319.950012  137.850006  53.900002  792.299988
2021-03-17      9.85    305.799988  133.850006  50.099998  772.150024
2021-03-18      9.90    307.000000  129.800003  52.099998  755.150024
2021-03-19      9.75    308.950012  127.949997  52.000000  760.650024

Attributes                                                                  \
Symbols        SBIN.NS MOTHERSUMI.NS  RBLBANK.NS IBULHSGFIN.NS ASHOKLEY.NS
Date
2021-03-15  383.899994    218.550003  238.250000    218.149994  121.500000
2021-03-16  378.549988    221.649994  235.100006    222.550003  123.250000
2021-03-17  368.149994    220.550003  223.399994    214.800003  117.150002
2021-03-18  367.100006    216.149994  222.949997    214.850006  113.199997
2021-03-19  371.149994    211.649994  228.550003    215.250000  116.300003

Attributes  ...        Volume                                               \
Symbols     ... CHENNPETRO.NS APLLTD.NS     PVR.NS NAVINFLUOR.NS  ALKEM.NS
Date        ...
2021-03-15  ...      770482.0  259958.0  1012526.0       63457.0  136075.0
2021-03-16  ...      663874.0  189831.0  1949881.0       79019.0   86396.0
2021-03-17  ...     1806405.0  193046.0   605892.0      186529.0   57460.0
2021-03-18  ...     1009487.0  218621.0   730383.0      190067.0   85292.0
2021-03-19  ...     1225558.0  249572.0  2339760.0      218584.0  143667.0

Attributes
Symbols    SUDARSCHEM.NS GODREJCP.NS ADVENZYMES.NS    IIFL.NS      OIL.NS
Date
2021-03-15      137075.0    530082.0      448167.0   655250.0    834320.0
2021-03-16       77637.0    738129.0      256574.0  1249591.0    793066.0
2021-03-17      206688.0   1538154.0      373415.0   778025.0   1050078.0
2021-03-18      108821.0   2245397.0      307874.0   349001.0   1091102.0
2021-03-19       98867.0   1300769.0      319595.0  8379235.0  12205335.0

[5 rows x 1728 columns]

In [5]:
count = 0
values = []
for i in tickers:
    if stocks[-1:]["Open"][i][0] == stocks[-1:]["Low"][i][0]:
        count += 1
        values.append(i.split(".")[0])
        
print(count)
df.loc[df[df['Ticker'].isin(values)].index][['Ticker','Volume']].sort_values(["Volume"],ascending=False)

6

         Ticker   Volume
66      PRAJIND  6723470
78        DABUR  5418102
94      FRETAIL  3811743
243       OMAXE   806807
261  CUMMINSIND   633908
286        IIFL   509679

In [129]:
def open_equalsto_low(df):
    # Testing Open == Low Strategy
    count = 0
    count2 = 0
    for index, row in df[:-1].iterrows():
        if row['Low'] == row['Open']:
            count += 1
#             print(f"Open and Close Same day: {row['Open']}, {row['Close']}")
#             print(f"Open, Close and High next day: {df['Open'].iloc[index+1]}, {df['Close'].iloc[index+1]}, {df['High'].iloc[index+1]}")
            if(df['Open'].iloc[index+1] < df['High'].iloc[index+1] and (((df['High'].iloc[index+1] - df['Open'].iloc[index+1])/df['High'].iloc[index+1]) * 100)>1):
                count2 += 1
#             print(((df['High'].iloc[index+1] - df['Open'].iloc[index+1])/df['High'].iloc[index+1]) * 100)
#             print()
    return count,count2

In [148]:
def open_equalsto_high(df):
    # Testing Open == High Strategy
    count = 0
    count2 = 0
    for index, row in df[:-1].iterrows():
        if row['High'] == row['Open']:
            count += 1
#             print(f"Open and Close Same day: {row['Open']}, {row['Close']}")
#             print(f"Open, Close and High next day: {df['Open'].iloc[index+1]}, {df['Close'].iloc[index+1]}, {df['Low'].iloc[index+1]}")
            if(df['Open'].iloc[index+1] > df['Low'].iloc[index+1] and (((df['Open'].iloc[index+1] - df['Low'].iloc[index+1])/df['Open'].iloc[index+1]) * 100)>1):
                count2 += 1
#             print(((df['Open'].iloc[index+1] - df['Low'].iloc[index+1])/df['Open'].iloc[index+1]) * 100)
#             print()

    return count,count2

In [149]:
directory = 'Nifty500HistoricalStocks/'
# newStocks = []
a = 0
# for filename in os.listdir(directory):
for filename in newStocks:
    df = pd.read_excel(directory+filename+".xlsx")
    count,count2 = open_equalsto_high(df)
    if round((count2/count)*100) > 59:
        a += 1
#         newStocks.append(filename.split('.')[0])
        print(filename.split('.')[0])
        print(f"Total case: {count}")
        print(f"True case: {(count2)}")
        print(f"Success Rate: {round((count2/count)*100)}%")
        print()

ABCAPITAL
Total case: 31
True case: 20
Success Rate: 65%

ABFRL
Total case: 143
True case: 95
Success Rate: 66%

ADANIPORTS
Total case: 214
True case: 144
Success Rate: 67%

ADANIPOWER
Total case: 206
True case: 153
Success Rate: 74%

ADANITRANS
Total case: 102
True case: 74
Success Rate: 73%

ALKEM
Total case: 113
True case: 68
Success Rate: 60%

ALLCARGO
Total case: 533
True case: 374
Success Rate: 70%

AMARAJABAT
Total case: 538
True case: 356
Success Rate: 66%

APLLTD
Total case: 220
True case: 136
Success Rate: 62%

APOLLOTYRE
Total case: 482
True case: 339
Success Rate: 70%

ASHOKA
Total case: 330
True case: 228
Success Rate: 69%

ASHOKLEY
Total case: 562
True case: 418
Success Rate: 74%

ATGL
Total case: 21
True case: 14
Success Rate: 67%

AUROPHARMA
Total case: 535
True case: 350
Success Rate: 65%

BAJFINANCE
Total case: 672
True case: 419
Success Rate: 62%

BALKRISIND
Total case: 485
True case: 324
Success Rate: 67%

BALRAMCHIN
Total case: 470
True case: 329
Success Rate: 70%

BANDHANBNK
Total case: 61
True case: 48
Success Rate: 79%

BANKBARODA
Total case: 430
True case: 294
Success Rate: 68%

BANKINDIA
Total case: 391
True case: 294
Success Rate: 75%

BATAINDIA
Total case: 431
True case: 260
Success Rate: 60%

BDL
Total case: 65
True case: 39
Success Rate: 60%

BEL
Total case: 504
True case: 335
Success Rate: 66%

BEML
Total case: 444
True case: 304
Success Rate: 68%

BHEL
Total case: 451
True case: 299
Success Rate: 66%

BIOCON
Total case: 348
True case: 233
Success Rate: 67%

BIRLACORPN
Total case: 650
True case: 451
Success Rate: 69%

BLISSGVS
Total case: 311
True case: 222
Success Rate: 71%

BOMDYEING
Total case: 531
True case: 361
Success Rate: 68%

BPCL
Total case: 549
True case: 373
Success Rate: 68%

BRIGADE
Total case: 330
True case: 227
Success Rate: 69%

BSOFT
Total case: 526
True case: 385
Success Rate: 73%

CADILAHC
Total case: 548
True case: 348
Success Rate: 64%

CANBK
Total case: 341
True case: 230
Success Rate: 67%

CANFINHOME
Total case: 699
True case: 421
Success Rate: 60%

CAPLIPOINT
Total case: 208
True case: 150
Success Rate: 72%

CENTRALBK
Total case: 347
True case: 230
Success Rate: 66%

CENTURYPLY
Total case: 533
True case: 358
Success Rate: 67%

CENTURYTEX
Total case: 418
True case: 289
Success Rate: 69%

CHAMBLFERT
Total case: 502
True case: 313
Success Rate: 62%

CHENNPETRO
Total case: 486
True case: 328
Success Rate: 67%

CHOLAFIN
Total case: 618
True case: 415
Success Rate: 67%

CYIENT
Total case: 474
True case: 319
Success Rate: 67%

DBL
Total case: 78
True case: 52
Success Rate: 67%

DCBBANK
Total case: 264
True case: 195
Success Rate: 74%

DHANI
Total case: 537
True case: 367
Success Rate: 68%

DIVISLAB
Total case: 411
True case: 261
Success Rate: 64%

DLF
Total case: 174
True case: 108
Success Rate: 62%

EDELWEISS
Total case: 334
True case: 241
Success Rate: 72%

EIHOTEL
Total case: 806
True case: 497
Success Rate: 62%

EMAMILTD
Total case: 475
True case: 308
Success Rate: 65%

ESCORTS
Total case: 600
True case: 451
Success Rate: 75%

FDC
Total case: 636
True case: 414
Success Rate: 65%

GLENMARK
Total case: 470
True case: 332
Success Rate: 71%

GMDCLTD
Total case: 550
True case: 353
Success Rate: 64%

GMRINFRA
Total case: 312
True case: 231
Success Rate: 74%

GNFC
Total case: 514
True case: 349
Success Rate: 68%

GODREJCP
Total case: 632
True case: 407
Success Rate: 64%

GPPL
Total case: 297
True case: 194
Success Rate: 65%

GRANULES
Total case: 398
True case: 266
Success Rate: 67%

GRAPHITE
Total case: 710
True case: 478
Success Rate: 67%

GREAVESCOT
Total case: 561
True case: 396
Success Rate: 71%

GSFC
Total case: 677
True case: 473
Success Rate: 70%

GSPL
Total case: 343
True case: 238
Success Rate: 69%

GUJGASLTD
Total case: 112
True case: 73
Success Rate: 65%

HAVELLS
Total case: 608
True case: 421
Success Rate: 69%

HCLTECH
Total case: 430
True case: 281
Success Rate: 65%

HFCL
Total case: 701
True case: 485
Success Rate: 69%

HIMATSEIDE
Total case: 679
True case: 421
Success Rate: 62%

HINDCOPPER
Total case: 199
True case: 126
Success Rate: 63%

HINDPETRO
Total case: 465
True case: 307
Success Rate: 66%

HSCL
Total case: 486
True case: 347
Success Rate: 71%

HUDCO
Total case: 79
True case: 54
Success Rate: 68%

IBREALEST
Total case: 227
True case: 167
Success Rate: 74%

IBULHSGFIN
Total case: 117
True case: 75
Success Rate: 64%

ICICIGI
Total case: 40
True case: 28
Success Rate: 70%

IDEA
Total case: 275
True case: 196
Success Rate: 71%

IDFC
Total case: 336
True case: 246
Success Rate: 73%

IFCI
Total case: 598
True case: 468
Success Rate: 78%

IIFL
Total case: 410
True case: 313
Success Rate: 76%

INDHOTEL
Total case: 547
True case: 366
Success Rate: 67%

INDIACEM
Total case: 527
True case: 384
Success Rate: 73%

INDIANB
Total case: 330
True case: 251
Success Rate: 76%

INDIGO
Total case: 89
True case: 55
Success Rate: 62%

INDUSINDBK
Total case: 425
True case: 280
Success Rate: 66%

INDUSTOWER
Total case: 179
True case: 115
Success Rate: 64%

INOXLEISUR
Total case: 325
True case: 232
Success Rate: 71%

IOB
Total case: 537
True case: 347
Success Rate: 65%

IRB
Total case: 205
True case: 157
Success Rate: 77%

ITI
Total case: 580
True case: 417
Success Rate: 72%

JBCHEPHARM
Total case: 563
True case: 364
Success Rate: 65%

JINDALSAW
Total case: 433
True case: 297
Success Rate: 69%

JINDALSTEL
Total case: 544
True case: 349
Success Rate: 64%

JKPAPER
Total case: 554
True case: 348
Success Rate: 63%

JKTYRE
Total case: 476
True case: 308
Success Rate: 65%

JSL
Total case: 457
True case: 342
Success Rate: 75%

JSLHISAR
Total case: 80
True case: 52
Success Rate: 65%

JSWENERGY
Total case: 179
True case: 124
Success Rate: 69%

JSWSTEEL
Total case: 391
True case: 264
Success Rate: 68%

JUBLFOOD
Total case: 124
True case: 81
Success Rate: 65%

JYOTHYLAB
Total case: 345
True case: 228
Success Rate: 66%

KALPATPOWR
Total case: 725
True case: 479
Success Rate: 66%

KOTAKBANK
Total case: 505
True case: 318
Success Rate: 63%

KRBL
Total case: 667
True case: 420
Success Rate: 63%

KSCL
Total case: 453
True case: 325
Success Rate: 72%

LICHSGFIN
Total case: 451
True case: 301
Success Rate: 67%

M&M
Total case: 525
True case: 320
Success Rate: 61%

M&MFIN
Total case: 392
True case: 265
Success Rate: 68%

MAHABANK
Total case: 699
True case: 486
Success Rate: 70%

MANAPPURAM
Total case: 247
True case: 165
Success Rate: 67%

MMTC
Total case: 239
True case: 151
Success Rate: 63%

MUTHOOTFIN
Total case: 178
True case: 118
Success Rate: 66%

NATIONALUM
Total case: 635
True case: 428
Success Rate: 67%

NAUKRI
Total case: 447
True case: 299
Success Rate: 67%

NAVINFLUOR
Total case: 437
True case: 277
Success Rate: 63%

NBCC
Total case: 163
True case: 113
Success Rate: 69%

NBVENTURES
Total case: 717
True case: 484
Success Rate: 68%

NFL
Total case: 456
True case: 338
Success Rate: 74%

NH
Total case: 177
True case: 112
Success Rate: 63%

NIACL
Total case: 84
True case: 60
Success Rate: 71%

PFC
Total case: 192
True case: 136
Success Rate: 71%

PNB
Total case: 341
True case: 226
Success Rate: 66%

PNBHOUSING
Total case: 94
True case: 72
Success Rate: 77%

POLYMED
Total case: 343
True case: 233
Success Rate: 68%

PRAJIND
Total case: 483
True case: 351
Success Rate: 73%

PRESTIGE
Total case: 251
True case: 187
Success Rate: 75%

PTC
Total case: 401
True case: 289
Success Rate: 72%

PVR
Total case: 359
True case: 261
Success Rate: 73%

RALLIS
Total case: 643
True case: 441
Success Rate: 69%

RAMCOCEM
Total case: 677
True case: 431
Success Rate: 64%

RAYMOND
Total case: 621
True case: 408
Success Rate: 66%

RCF
Total case: 496
True case: 364
Success Rate: 73%

RECLTD
Total case: 193
True case: 124
Success Rate: 64%

SAIL
Total case: 637
True case: 448
Success Rate: 70%

SBICARD
Total case: 8
True case: 5
Success Rate: 62%

SBILIFE
Total case: 63
True case: 39
Success Rate: 62%

SCI
Total case: 481
True case: 332
Success Rate: 69%

SEQUENT
Total case: 102
True case: 75
Success Rate: 74%

SRF
Total case: 386
True case: 250
Success Rate: 65%

SRTRANSFIN
Total case: 610
True case: 398
Success Rate: 65%

STLTECH
Total case: 479
True case: 364
Success Rate: 76%

SUMICHEM
Total case: 16
True case: 11
Success Rate: 69%

SUNTV
Total case: 260
True case: 169
Success Rate: 65%

SYNGENE
Total case: 114
True case: 68
Success Rate: 60%

TAKE
Total case: 468
True case: 338
Success Rate: 72%

TATACONSUM
Total case: 568
True case: 360
Success Rate: 63%

TATAELXSI
Total case: 401
True case: 276
Success Rate: 69%

TATAMOTORS
Total case: 528
True case: 358
Success Rate: 68%

TATAPOWER
Total case: 539
True case: 358
Success Rate: 66%

TECHM
Total case: 269
True case: 171
Success Rate: 64%

TITAN
Total case: 508
True case: 349
Success Rate: 69%

TORNTPHARM
Total case: 639
True case: 406
Success Rate: 64%

TORNTPOWER
Total case: 224
True case: 160
Success Rate: 71%

TRIDENT
Total case: 796
True case: 572
Success Rate: 72%

TV18BRDCST
Total case: 297
True case: 209
Success Rate: 70%

TVSMOTOR
Total case: 690
True case: 494
Success Rate: 72%

UJJIVAN
Total case: 66
True case: 46
Success Rate: 70%

UNIONBANK
Total case: 386
True case: 282
Success Rate: 73%

VIPIND
Total case: 553
True case: 372
Success Rate: 67%

VOLTAS
Total case: 479
True case: 334
Success Rate: 70%

WELSPUNIND
Total case: 608
True case: 443
Success Rate: 73%

WESTLIFE
Total case: 43
True case: 35
Success Rate: 81%

WOCKPHARMA
Total case: 490
True case: 315
Success Rate: 64%

ZEEL
Total case: 392
True case: 263
Success Rate: 67%

In [150]:
len(newStocks)

174

In [151]:
a

164

In [138]:
newStocks

['ABCAPITAL',
 'ABFRL',
 'ADANIPORTS',
 'ADANIPOWER',
 'ADANITRANS',
 'ADVENZYMES',
 'ALKEM',
 'ALLCARGO',
 'AMARAJABAT',
 'APLLTD',
 'APOLLOTYRE',
 'ASHOKA',
 'ASHOKLEY',
 'ATGL',
 'AUROPHARMA',
 'BAJAJFINSV',
 'BAJFINANCE',
 'BALKRISIND',
 'BALRAMCHIN',
 'BANDHANBNK',
 'BANKBARODA',
 'BANKINDIA',
 'BATAINDIA',
 'BDL',
 'BEL',
 'BEML',
 'BHEL',
 'BIOCON',
 'BIRLACORPN',
 'BLISSGVS',
 'BOMDYEING',
 'BPCL',
 'BRIGADE',
 'BSOFT',
 'CADILAHC',
 'CANBK',
 'CANFINHOME',
 'CAPLIPOINT',
 'CDSL',
 'CENTRALBK',
 'CENTURYPLY',
 'CENTURYTEX',
 'CHAMBLFERT',
 'CHENNPETRO',
 'CHOLAFIN',
 'CYIENT',
 'DBL',
 'DCBBANK',
 'DHANI',
 'DIVISLAB',
 'DLF',
 'EDELWEISS',
 'EIHOTEL',
 'EMAMILTD',
 'ESCORTS',
 'FDC',
 'FORTIS',
 'GLENMARK',
 'GMDCLTD',
 'GMRINFRA',
 'GNFC',
 'GODREJCP',
 'GPPL',
 'GRANULES',
 'GRAPHITE',
 'GREAVESCOT',
 'GRSE',
 'GSFC',
 'GSPL',
 'GUJGASLTD',
 'HAVELLS',
 'HCLTECH',
 'HFCL',
 'HIMATSEIDE',
 'HINDCOPPER',
 'HINDPETRO',
 'HSCL',
 'HUDCO',
 'IBREALEST',
 'IBULHSGFIN',
 'ICICIGI',
 'IDEA',
 'IDFC',
 'IFCI',
 'IGL',
 'IIFL',
 'INDHOTEL',
 'INDIACEM',
 'INDIANB',
 'INDIGO',
 'INDUSINDBK',
 'INDUSTOWER',
 'INOXLEISUR',
 'IOB',
 'IRB',
 'ITI',
 'JBCHEPHARM',
 'JINDALSAW',
 'JINDALSTEL',
 'JKPAPER',
 'JKTYRE',
 'JSL',
 'JSLHISAR',
 'JSWENERGY',
 'JSWSTEEL',
 'JUBLFOOD',
 'JYOTHYLAB',
 'KALPATPOWR',
 'KOTAKBANK',
 'KRBL',
 'KSCL',
 'LICHSGFIN',
 'M&M',
 'M&MFIN',
 'MAHABANK',
 'MANAPPURAM',
 'MIDHANI',
 'MMTC',
 'MUTHOOTFIN',
 'NATIONALUM',
 'NAUKRI',
 'NAVINFLUOR',
 'NBCC',
 'NBVENTURES',
 'NFL',
 'NH',
 'NIACL',
 'PFC',
 'PHILIPCARB',
 'PNB',
 'PNBHOUSING',
 'POLYMED',
 'PRAJIND',
 'PRESTIGE',
 'PTC',
 'PVR',
 'RALLIS',
 'RAMCOCEM',
 'RAYMOND',
 'RCF',
 'RECLTD',
 'SAIL',
 'SBICARD',
 'SBILIFE',
 'SCI',
 'SEQUENT',
 'SRF',
 'SRTRANSFIN',
 'STLTECH',
 'SUMICHEM',
 'SUNTV',
 'SYNGENE',
 'TAKE',
 'TATACONSUM',
 'TATAELXSI',
 'TATAMOTORS',
 'TATAPOWER',
 'TATASTEEL',
 'TECHM',
 'TITAN',
 'TORNTPHARM',
 'TORNTPOWER',
 'TRIDENT',
 'TV18BRDCST',
 'TVSMOTOR',
 'UJJIVAN',
 'UNIONBANK',
 'VAKRANGEE',
 'VIPIND',
 'VOLTAS',
 'WELSPUNIND',
 'WESTLIFE',
 'WOCKPHARMA',
 'ZEEL']